#!/bin/bash

set -e

: "${OPENAI_API_KEY:?OPENAI_API_KEY must be set before running this script}"
export LANGFUSE_BASE_URL="${LANGFUSE_BASE_URL:-http://localhost:3000}"
export LANGFUSE_PUBLIC_KEY="${LANGFUSE_PUBLIC_KEY:-pk-lf-local-tracing-project}"
export LANGFUSE_SECRET_KEY="${LANGFUSE_SECRET_KEY:-sk-lf-local-tracing-project-secret}"

INDEX="soccer_drills_test"

QUERIES=(
  "What are the key coaching points for soccer passing drills?"
  "How do you set up a breaking ball drill?"
  "What are drill variations for defensive pressure training?"
  "Explain attacking vs defending drills"
  "What dribbling exercises improve ball control?"
  "How do you coach youth players on shooting accuracy?"
  "What warm-up drills are recommended before practice?"
  "Describe positional play exercises for midfielders"
  "What are effective small-sided game setups?"
  "How do you run a rondo drill?"
  "What are the best drills for improving first touch?"
  "How do you teach overlapping runs to players?"
  "What exercises improve players' spatial awareness?"
  "Describe a drill that combines passing and movement"
  "How do you coach pressing and high press tactics?"
  "What drills build endurance for soccer players?"
  "How do you practice set pieces in training?"
  "What are the main principles of defensive organization?"
  "How do you train transition from defense to attack?"
  "What drills help improve crossing accuracy?"
  "Describe a shooting drill for strikers"
  "How do you coach goalkeepers in training sessions?"
  "What are effective heading drills?"
  "How do you improve players' weak foot?"
  "What is a good drill for improving communication on the pitch?"
  "How do you set up a 1v1 defending drill?"
  "What exercises build confidence in young players?"
  "Describe a drill focusing on combination play"
  "How do you coach players on making runs in behind?"
  "What are good possession drills for a beginner team?"
  "How do you train penalty kicks effectively?"
  "What drills help players deal with high-pressure situations?"
  "Describe a drill for improving throw-ins"
  "How do you practice corner kick routines?"
  "What exercises improve a player's stamina?"
  "How do you coach width and depth in attacking play?"
  "What are some cool-down drills after a session?"
  "How do you structure a 90-minute training session?"
  "What drills improve a team's shape out of possession?"
  "Describe a pressing trap drill"
  "How do you coach wingers to cut inside effectively?"
  "What passing patterns improve buildup play?"
  "Describe an exercise for improving off-the-ball movement"
  "How do you use cones in agility training for soccer?"
  "What is a box drill and how is it used?"
  "How do you coach players on when to dribble vs pass?"
  "What drills help improve a team's defensive shape?"
  "How do you practice long balls and switches of play?"
  "Describe a drill that combines defending and quick counter-attack"
  "What are effective plyometric exercises for soccer players?"
  "How do you coach players to track runners from midfield?"
  "What drills help improve a player's reaction time?"
  "How do you run a shadow play exercise?"
  "Describe a drill for developing tactical awareness"
  "How do you coach a 4-3-3 formation in training?"
  "What exercises build strength for soccer-specific movements?"
  "How do you practice dealing with long balls into the box?"
  "What are drills for improving a goalkeeper's distribution?"
  "Describe a session focused on building from the back"
  "How do you coach pressing triggers?"
  "What drills help fullbacks with attacking and defending?"
  "Describe an exercise for improving link-up play between striker and midfield"
  "How do you train switching the point of attack quickly?"
  "What drills are good for teaching compactness?"
  "How do you coach the offside trap?"
  "What passing combinations improve a team's rhythm?"
  "How do you set up a defending in wide areas drill?"
  "Describe a session for improving transitions in midfield"
  "What drills help players improve their decision-making?"
  "How do you train players to win second balls?"
  "What are effective overload drills (e.g., 3v2)?"
  "How do you coach players to press the opponent's goalkeeper?"
  "What are the key technical skills for a central defender?"
  "How do you structure positional training for attackers?"
  "Describe a drill that works on combination play in the final third"
  "What exercises are best for improving a player's balance?"
  "How do you coach players on defensive headers?"
  "What drills help a team stay organized when defending set pieces?"
  "Describe a session that improves a team's finishing under pressure"
  "How do you train the offside line in defense?"
  "What drills help players press as a unit?"
  "How do you coach central midfielders to receive under pressure?"
  "What technical drills are suitable for U10 players?"
  "How do you teach players to create overloads wide?"
  "What are effective drills for improving throw-in routines?"
  "Describe a session on defensive transitions"
  "How do you coach quick combination play in tight spaces?"
  "What are effective conditioning drills using the ball?"
  "How do you improve a player's ability to beat a defender 1v1?"
  "What drills build confidence for players new to a team?"
  "Describe a game-based drill that improves pressing and counter-pressing"
  "How do you train team shape in possession?"
  "What drills help defenders deal with quick attackers?"
  "Describe a pattern of play for breaking down a low block"
  "How do you coach dynamic movement without the ball?"
  "What exercises improve a player's acceleration on the pitch?"
  "How do you practice defensive covering and marking?"
  "What are drills for improving a team's set-piece defending?"
  "How do you coach players to exploit space behind the defensive line?"
  "Describe a session focusing on goalkeeper footwork and positioning"
  "What drills are most effective for improving one-touch passing?"
  "How do you run a passing triangle drill?"
  "What exercises help central defenders step up to press effectively?"
  "Describe a session on exploiting numerical advantages"
  "How do you train players to stay compact while defending?"
  "What tactical drills help a team defend against wing play?"
  "Describe a drill for improving finishing from crosses"
  "How do you coach players on anticipating the ball's trajectory?"
  "What passing exercises work best for improving tempo in buildup?"
  "How do you set up a drill for training defensive header duels?"
  "What exercises develop a player's aerial ability?"
  "Describe a session that combines fitness and technical skill work"
  "How do you coach players to defend deeper blocks?"
  "What are effective breakout drills after winning possession?"
  "How do you practice sustained possession under pressure?"
  "Describe a drill focused on striker movement and goal scoring"
  "What exercises improve a team's offside trap timing?"
  "How do you train midfielders to cover ground quickly?"
  "What are good drills for practicing quick free kicks?"
  "How do you coach players on picking the right pass?"
  "What exercises help build chemistry between striker and supporting midfielder?"
  "Describe a drill for improving goalkeeping under high crosses"
  "How do you train players to execute quick throw-ins effectively?"
  "What drills best simulate real match scenarios?"
  "How do you coach defenders on dealing with pacey strikers?"
  "Describe a rondo variation to improve pressure resistance"
  "What exercises help a team press higher up the pitch?"
  "How do you structure a session focused on defending corners?"
  "What passing drills prepare a team for an away game?"
  "Describe a drill where the team practices maintaining shape while attacking"
  "How do you coach players to make late runs into the box?"
  "What exercises develop composure in front of goal?"
  "Describe a session focused on quick transitions from set pieces"
  "How do you use small-sided games to improve defensive intensity?"
  "What technical drills are most used at elite youth academies?"
  "How do you coach a flat back four to hold their line?"
  "What are key passing drills for a possession-based system?"
  "Describe a session that builds resilience and mental toughness in players"
  "How do you use video analysis to complement training drills?"
  "What are the best drills for end-to-end transitions?"
  "How do you coach goalkeepers to command their penalty area?"
  "Describe an exercise for improving movement off the ball in attack"
  "What drills help players communicate more effectively on the pitch?"
  "How do you train a team to deal with long throw-ins?"
  "What tactical patterns exploit a high defensive line?"
)

TOTAL=${#QUERIES[@]}
COUNT=0
START_FROM=${1:-0}  # pass start index as first arg to resume

source venv/bin/activate

for i in $(seq $START_FROM 149); do
  IDX=$((i % TOTAL))
  QUERY="${QUERIES[$IDX]}"
  COUNT=$((i + 1))
  echo ""
  echo "=== Run $COUNT/150 ==="
  echo "Query: $QUERY"
  echo "----------------------------------------"
  python vanilla_langgraph_pgvector_rag.py \
    --langfuse \
    --index-name "$INDEX" \
    --query "$QUERY" 2>&1
  echo ""
  echo "--- Done $COUNT/ ---"
done

echo ""
echo "All 150 runs complete. Check Langfuse at http://localhost:3000"
